[package]
name = "ctrait"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34.5", features = ["image"] }
timer = "0.2.0"
chrono = "0.4.19"
cgmath = "0.18.0"
